/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CtdAnimation {
        /**
          * Wether the animation should start automatically.
         */
        "autoplay": boolean;
        /**
          * The animation data as JSON-parsable string.
         */
        "data": string;
        /**
          * The height of the animation.
         */
        "height": string;
        /**
          * Wether the animation should repeat infinitely
         */
        "loop": boolean;
        /**
          * The URL to a JSON file, containing the animation data.
         */
        "url": string;
        /**
          * The width of the animation.
         */
        "width": string;
    }
}
declare global {
    interface HTMLCtdAnimationElement extends Components.CtdAnimation, HTMLStencilElement {
    }
    var HTMLCtdAnimationElement: {
        prototype: HTMLCtdAnimationElement;
        new (): HTMLCtdAnimationElement;
    };
    interface HTMLElementTagNameMap {
        "ctd-animation": HTMLCtdAnimationElement;
    }
}
declare namespace LocalJSX {
    interface CtdAnimation {
        /**
          * Wether the animation should start automatically.
         */
        "autoplay"?: boolean;
        /**
          * The animation data as JSON-parsable string.
         */
        "data"?: string;
        /**
          * The height of the animation.
         */
        "height"?: string;
        /**
          * Wether the animation should repeat infinitely
         */
        "loop"?: boolean;
        /**
          * The URL to a JSON file, containing the animation data.
         */
        "url"?: string;
        /**
          * The width of the animation.
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "ctd-animation": CtdAnimation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ctd-animation": LocalJSX.CtdAnimation & JSXBase.HTMLAttributes<HTMLCtdAnimationElement>;
        }
    }
}
