/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlyAnimation {
        /**
          * Wether the animation should start automatically.
         */
        "autoplay": boolean;
        /**
          * The animation data as JSON-parsable string.
         */
        "data": string;
        /**
          * The height of the animation.
         */
        "height": string;
        /**
          * Wether the animation should repeat infinitely
         */
        "loop": boolean;
        /**
          * The name of the animation.
         */
        "name": string;
        /**
          * Pauses the animation.
          * @return
         */
        "pause": () => Promise<void>;
        /**
          * Plays the animation.
          * @return
         */
        "play": () => Promise<void>;
        /**
          * Stops the animation.
          * @return
         */
        "stop": () => Promise<void>;
        /**
          * The URL to a JSON file, containing the animation data.
         */
        "url": string;
        /**
          * The width of the animation.
         */
        "width": string;
    }
}
declare global {
    interface HTMLFlyAnimationElement extends Components.FlyAnimation, HTMLStencilElement {
    }
    var HTMLFlyAnimationElement: {
        prototype: HTMLFlyAnimationElement;
        new (): HTMLFlyAnimationElement;
    };
    interface HTMLElementTagNameMap {
        "fly-animation": HTMLFlyAnimationElement;
    }
}
declare namespace LocalJSX {
    interface FlyAnimation {
        /**
          * Wether the animation should start automatically.
         */
        "autoplay"?: boolean;
        /**
          * The animation data as JSON-parsable string.
         */
        "data"?: string;
        /**
          * The height of the animation.
         */
        "height"?: string;
        /**
          * Wether the animation should repeat infinitely
         */
        "loop"?: boolean;
        /**
          * The name of the animation.
         */
        "name"?: string;
        /**
          * The URL to a JSON file, containing the animation data.
         */
        "url"?: string;
        /**
          * The width of the animation.
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "fly-animation": FlyAnimation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fly-animation": LocalJSX.FlyAnimation & JSXBase.HTMLAttributes<HTMLFlyAnimationElement>;
        }
    }
}
